-- MySQL Script generated by MySQL Workbench
-- Thu Dec 15 13:10:33 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DVD_Store_Schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Director`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Director`;

CREATE TABLE IF NOT EXISTS `Director` (
  `id`        INT         NOT NULL AUTO_INCREMENT,
  `name`      VARCHAR(60) NOT NULL,
  `biography` LONGTEXT    NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Genre`;

CREATE TABLE IF NOT EXISTS `Genre` (
  `id`   INT         NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Studio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Studio`;

CREATE TABLE IF NOT EXISTS `Studio` (
  `id`   INT         NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE`
  ON `Studio` (`id` ASC);

-- -----------------------------------------------------
-- Table `Classification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classification`;

CREATE TABLE IF NOT EXISTS `Classification` (
  `id`          INT         NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Rate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rate`;

CREATE TABLE IF NOT EXISTS `Rate` (
  `id`   INT NOT NULL AUTO_INCREMENT,
  `rate` INT NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Movie`;

CREATE TABLE IF NOT EXISTS `Movie` (
  `id`                VARCHAR(20)  NOT NULL,
  `title`             VARCHAR(150) NOT NULL,
  `dvd_count`         INT          NOT NULL,
  `short_description` VARCHAR(45)  NULL,
  `release_date`      DATETIME     NULL,
  `runtime`           INT          NULL,
  `director_id`       INT          NOT NULL,
  `genre_id`          INT          NULL,
  `label_id`          INT          NULL,
  `studio_id`         INT          NULL,
  `classification_id` INT          NOT NULL,
  `rate_id`           INT          NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_Catalogue_director`
  FOREIGN KEY (`director_id`)
  REFERENCES `Director` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Catalogue_genre`
  FOREIGN KEY (`genre_id`)
  REFERENCES `Genre` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Catalogue_studio`
  FOREIGN KEY (`studio_id`)
  REFERENCES `Studio` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Catalogue_classification`
  FOREIGN KEY (`classification_id`)
  REFERENCES `Classification` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Catalogue_rate`
  FOREIGN KEY (`rate_id`)
  REFERENCES `Rate` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
)
  ENGINE = InnoDB;

CREATE INDEX `FK_director_idx`
  ON `Movie` (`director_id` ASC);

CREATE INDEX `FK_genre_idx`
  ON `Movie` (`genre_id` ASC);

CREATE INDEX `FK_studio_idx`
  ON `Movie` (`studio_id` ASC);

CREATE INDEX `FK_classification_idx`
  ON `Movie` (`classification_id` ASC);

CREATE INDEX `FK_rate_idx`
  ON `Movie` (`rate_id` ASC);

-- -----------------------------------------------------
-- Table `Supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Supplier`;

CREATE TABLE IF NOT EXISTS `Supplier` (
  `id`   INT          NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Stock Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Stock Item`;

CREATE TABLE IF NOT EXISTS `Stock Item` (
  `id`           INT         NOT NULL AUTO_INCREMENT,
  `catalog_id`   VARCHAR(20) NOT NULL,
  `supplier_id`  INT         NOT NULL,
  `date_aquired` DATETIME    NULL,
  `cost`         INT         NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_Stock_catalogue`
  FOREIGN KEY (`catalog_id`)
  REFERENCES `Movie` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Stock_supplier`
  FOREIGN KEY (`supplier_id`)
  REFERENCES `Supplier` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
)
  ENGINE = InnoDB;

CREATE INDEX `FK_catalogue_idx`
  ON `Stock Item` (`catalog_id` ASC);

CREATE INDEX `FK_supplier_idx`
  ON `Stock Item` (`supplier_id` ASC);

-- -----------------------------------------------------
-- Table `Member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Member`;

CREATE TABLE IF NOT EXISTS `Member` (
  `id`          INT          NOT NULL,
  `first_name`  VARCHAR(60)  NOT NULL,
  `last_name`   VARCHAR(60)  NOT NULL,
  `address`     VARCHAR(100) NOT NULL,
  `phone`       VARCHAR(30)  NULL,
  `email`       VARCHAR(60)  NULL,
  `dob`         DATE         NULL,
  `max_rentals` INT          NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Rental`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rental`;

CREATE TABLE IF NOT EXISTS `Rental` (
  `id`          INT          NOT NULL AUTO_INCREMENT,
  `stock_id`    INT          NOT NULL,
  `member_id`   INT          NOT NULL,
  `issue_date`  DATETIME     NOT NULL,
  `return_date` DATETIME     NOT NULL,
  `notes`       VARCHAR(255) NOT NULL,
  `charge`      INT          NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_Rental_stock`
  FOREIGN KEY (`stock_id`)
  REFERENCES `Stock Item` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Rental_member`
  FOREIGN KEY (`member_id`)
  REFERENCES `Member` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
  ENGINE = InnoDB;

CREATE INDEX `FK_stock_idx`
  ON `Rental` (`stock_id` ASC);

CREATE INDEX `FK_member_idx`
  ON `Rental` (`member_id` ASC);

-- -----------------------------------------------------
-- Table `Reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Reservation`;

CREATE TABLE IF NOT EXISTS `Reservation` (
  `id`             INT         NOT NULL AUTO_INCREMENT,
  `catalogue_id`   VARCHAR(45) NOT NULL,
  `member_id`      INT         NOT NULL,
  `date_requested` DATETIME    NOT NULL,
  `date_issued`    DATETIME    NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_Reservation_catalogue`
  FOREIGN KEY (`catalogue_id`)
  REFERENCES `Movie` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Reservation_member`
  FOREIGN KEY (`member_id`)
  REFERENCES `Member` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
)
  ENGINE = InnoDB;

CREATE INDEX `FK_catalogue_idx`
  ON `Reservation` (`catalogue_id` ASC);

CREATE INDEX `FK_member_idx`
  ON `Reservation` (`member_id` ASC);

-- -----------------------------------------------------
-- Table `Actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Actor`;

CREATE TABLE IF NOT EXISTS `Actor` (
  `id`        INT         NOT NULL AUTO_INCREMENT,
  `name`      VARCHAR(60) NOT NULL,
  `biography` LONGTEXT    NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Review`;

CREATE TABLE IF NOT EXISTS `Review` (
  `id`           INT         NOT NULL AUTO_INCREMENT,
  `catalogue_id` VARCHAR(20) NOT NULL,
  `text`         LONGTEXT    NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_Review_catalogue`
  FOREIGN KEY (`catalogue_id`)
  REFERENCES `Movie` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
)
  ENGINE = InnoDB;

CREATE INDEX `FK_catalogue_idx`
  ON `Review` (`catalogue_id` ASC);

-- -----------------------------------------------------
-- Table `Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Role`;

CREATE TABLE IF NOT EXISTS `Role` (
  `actor_id`     INT         NOT NULL,
  `catalogue_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`actor_id`, `catalogue_id`),
  CONSTRAINT `FK_Role_actor`
  FOREIGN KEY (`actor_id`)
  REFERENCES `Actor` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Role_catalogue`
  FOREIGN KEY (`catalogue_id`)
  REFERENCES `Movie` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
)
  ENGINE = InnoDB;

CREATE INDEX `FK_catalogue_idx`
  ON `Role` (`catalogue_id` ASC);


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
